### ISSUE TITLE
Please add filename to warning output

### ISSUE THREAD

**Issue by jeremyruppel** [yahoo/secure-handlebars#122]
Is it possible to include the offending template filename with the warning output? I made a change in our test suite and got a blast of errors like this:

```
[WARNING] SecureHandlebars: Unsafe output expression found at scriptable <script> tag
Please follow this URL to resolve - https://github.com/yahoo/secure-handlebars#warnings-and-workarounds [lineNo:45,charNo:869]
```

It would be very helpful to also include the path to the offending file along with the line and column numbers.

**Comment by neraliu** [comment]
PR for this - https://github.com/yahoo/secure-handlebars/pull/125

**Comment by neraliu** [comment]
it is now supported in secure-handlebars 1.1.1 and express-secure-handlebars 2.0.4
